---
name: module3_task0
on:
  push:
    branches:
      - main
  schedule:
    # * is special character quote it!
    # trigger the workflow every day at 5:30 and 17:30 UTC
    - cron: '30 10 * * *'

jobs:
  module3_task0_display_help:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the help target
        uses: actions/checkout@v3
      - name: cd to directory containing symlink
        run: |
          cd module3_task0
          make help
