---
name: module3_task1
"on":
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Validate Makefile help
        run: |
          ./setup.sh
          make help
          make build
          make clean
          make post